simple_cms/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root "demo#index"

end

simple_cms/app/models/user.rb
class User < ActiveRecord::Base
end

simple_cms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

simple_cms/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	layout false
	def new
	end
	def create
		render plain: params[:article].inspect
	end
end

simple_cms/app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
  end
end

simple_cms/app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  layout false
  def hello
  end
end

simple_cms/app/helpers/application_helper.rb
module ApplicationHelper
end

simple_cms/app/helpers/articles_helper.rb
module ArticlesHelper
end

simple_cms/app/helpers/demo_helper.rb
module DemoHelper
end

simple_cms/app/helpers/greeter_helper.rb
module GreeterHelper
end

simple_cms/app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

simple_cms/app/views/demo/hello.html.erb
<h1>Demo#hello</h1>
<p>Hello from index!</p>
<p><%= Time.now %></p>

simple_cms/app/views/demo/index.html.erb
<h1>Demo Index Page</h1>
<p>My first ruby on rails page!</p>
<p>Current Time: <%= Time.now %></p>

simple_cms/app/views/greeter/hello.html.erb
<h1>Greeter#hello</h1>
<p>Find me in app/views/greeter/hello.html.erb</p>

simple_cms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleCms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>